pool:
    vmImage: 'Ubuntu 16.04'

variables:
    Version: '3.0.$(Build.BuildId)'
    ImageName: biowareru/bioengine-brc-bw:$(Version)

steps:
    - task: UseDotNet@2
      displayName: 'install .net core 3.0'
      inputs:
          packageType: sdk
          version: 3.0.100-preview5-011568
          includePreviewVersions: true

    - task: UseNode@1
      displayName: 'install node'
      inputs:
          version: '11.x'
          checkLatest: true

    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
          command: restore
          projects: '**/*.csproj'
          feedsToUse: 'select'
          verbosityRestore: 'minimal'
          vstsFeed: 'BioEngine'

    - task: Npm@1
      displayName: 'install npm packages'
      inputs:
          command: 'custom'
          customCommand: 'ci'

    - task: Npm@1
      displayName: 'build frontend'
      inputs:
          command: 'custom'
          customCommand: 'run build-prod'

    - task: DotNetCoreCLI@2
      displayName: 'publish app'
      inputs:
          command: custom
          custom: publish
          publishWebProjects: false
          zipAfterPublish: false
          modifyOutputPath: false
          arguments: '--no-restore -c Release --output ./publish'
          projects: '**/*.csproj'

    - script: |
          docker build -f src/BioEngine.BRC.BioWare/Dockerfile ./publish -t $(ImageName)
      displayName: 'build docker image'

    - script: |
          docker login -u $(dockerId) -p $(dockerPswd)
      displayName: 'login to docker hub'

    - script: |
          docker push $(ImageName)
      displayName: 'push image to docker hub'
    
